export const jwtConstants = {
    secret: 'eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTY5MzYwMTI1OCwiaWF0IjoxNjkzNjAxMjU4fQ.a30qe1zkilkpNm4kBeLxFrUwgTq2He2VZ5I-gBLrzXo'
  };